[package]
name = "sl-marketplace"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Sans-I/O model of the Second Life Marketplace (SLM) DirectDelivery JSON REST API"
readme = { workspace = true }
license = { workspace = true }

repository = { workspace = true }
keywords = ["json", "marketplace", "sans-io", "secondlife", "slm"]
categories = ["api-bindings", "encoding"]
publish = { workspace = true }

exclude = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sl-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
