//! The **About floater** (`viewer-about-floater`): viewer name and version
//! (build-time `git describe`), the connected grid and region with its
//! simulator version, runtime system information (OS, CPU, memory, GPU as
//! reported by wgpu) — all copyable to the clipboard as one block, the
//! support workflow the reference's "Copy to Clipboard" exists for — plus
//! credits and the third-party license texts generated by `cargo about`
//! (`scripts/generate-third-party-licenses.sh`, embedded at compile time).
//!
//! The copyable support block deliberately uses **English labels** regardless
//! of the UI locale, so pasted blocks stay grep-able / comparable for support
//! staff; the surrounding chrome (title, tab labels, buttons, credits) is
//! Fluent-localised like the rest of the UI.
//!
//! Reference (Firestorm, read-only): `llfloaterabout.{h,cpp}`,
//! `floater_about.xml`, `LLAppViewer::getViewerInfoString`.

use std::net::SocketAddr;

use bevy::diagnostic::SystemInfo;
use bevy::input_focus::tab_navigation::TabIndex;
use bevy::prelude::*;
use bevy::render::renderer::RenderAdapterInfo;
use bevy::ui_widgets::{Button, ControlOrientation, Scrollbar, ScrollbarThumb};

use crate::build_info;
use crate::clipboard::{ViewerClipboard, copy_to_clipboard};
use crate::floater::{
    DeferredFloaterContent, FloaterCaps, FloaterHandle, FloaterSpec, floater_shown, spawn_floater,
};
use crate::i18n::{Translated, UiLocale};
use crate::preferences::{CONTROL_BORDER, FONT, LABEL_COLOR};
use crate::ui::{UiRoot, UiScaffoldSystems, column, row};
use crate::ui_font::UiFont;
use crate::ui_tab::{
    DEFAULT_ELLIPSIS, TabPlacement, TabSpec, fill_tab_container, spawn_tab_container,
};
use sl_client_bevy::{SlCurrentRegion, SlEvent, SlRegionIdentity, SlSessionEvent};

/// The floater's stable id (menu toggle, geometry persistence, tests).
pub(crate) const ABOUT_FLOATER_ID: &str = "about";

/// The generated third-party license file (committed; regenerate with
/// `scripts/generate-third-party-licenses.sh` after dependency changes — the
/// ggh `rust:::cargo-about-outdated` check enforces freshness).
const THIRD_PARTY_LICENSES: &str = include_str!("../assets/licenses/third-party-licenses.txt");

/// The workspace's own license text (LGPL-2.1-only), the first Licenses entry.
const PROJECT_LICENSE: &str = include_str!("../../LICENSE");

/// The support-block value shown for session facts that do not exist yet
/// (before login, or before the grid supplied them).
const NOT_CONNECTED: &str = "(not connected)";

/// The scrollbar thickness for this floater's scroll panes, in logical pixels.
const SCROLLBAR_THICKNESS: f32 = 8.0;

/// The scrollbar thumb's minimum length, in logical pixels.
const SCROLLBAR_MIN_THUMB: f32 = 24.0;

/// The scrollbar track colour.
const SCROLLBAR_TRACK_COLOR: Color = Color::srgba(1.0, 1.0, 1.0, 0.06);

/// The scrollbar thumb colour.
const SCROLLBAR_THUMB_COLOR: Color = Color::srgba(1.0, 1.0, 1.0, 0.35);

/// The action buttons' background colour.
const BUTTON_BACKGROUND: Color = Color::srgb(0.16, 0.19, 0.25);

/// The license list's width, in logical pixels.
const LICENSE_LIST_WIDTH: f32 = 230.0;

/// The selected license row's background.
const LICENSE_ROW_SELECTED: Color = Color::srgba(0.35, 0.55, 0.90, 0.35);

/// An unselected license row's background.
const LICENSE_ROW_UNSELECTED: Color = Color::NONE;

/// The monospace font size of the support block and license texts.
const MONO_FONT: f32 = 12.0;

// ---------------------------------------------------------------------------
// Data model.
// ---------------------------------------------------------------------------

/// Login-derived session facts for the support block, inserted by
/// `run_session` before the app starts (absent in the gallery binary).
#[derive(Resource, Clone)]
pub(crate) struct AboutSessionInfo {
    /// The grid directory name derived from the login URI (`localhost`,
    /// `agni`, …).
    pub(crate) grid: String,
    /// The XML-RPC login URI the session used.
    pub(crate) login_uri: String,
    /// The viewer channel reported at login.
    pub(crate) channel: String,
    /// The viewer version reported at login.
    pub(crate) version: String,
}

/// One parsed license section of the Licenses tab.
#[derive(Debug, Clone, PartialEq, Eq)]
struct LicenseSection {
    /// The SPDX id (`Apache-2.0`), or a synthetic id for the project license.
    id: String,
    /// The human-readable license name (`Apache License 2.0`).
    name: String,
    /// The comma-separated `crate version` list using this license text (empty
    /// for the project license entry).
    used_by: String,
    /// The verbatim license text.
    text: String,
}

/// The About floater's model state: the latest session facts tracked from
/// events, the parsed license sections, and the currently rendered content
/// (for update-in-place change detection).
#[derive(Resource, Default)]
struct AboutState {
    /// The current root region simulator's version/channel string
    /// ([`SlSessionEvent::SimulatorVersion`]).
    simulator_version: Option<String>,
    /// The current root simulator's UDP address.
    sim_host: Option<SocketAddr>,
    /// The parsed license sections (project license first), filled on the
    /// first open alongside the content build.
    licenses: Vec<LicenseSection>,
    /// The selected Licenses-tab entry.
    selected_license: usize,
    /// The license entry currently rendered into the text pane, if any.
    rendered_license: Option<usize>,
    /// The support block currently rendered (and what Copy copies).
    rendered_block: String,
}

/// The built content's entity handles (inserted on first open).
#[derive(Resource)]
struct AboutUi {
    /// The support block's `Text` node.
    support_text: Entity,
    /// The license text pane's `Text` node.
    license_text: Entity,
    /// The license list rows, in [`AboutState::licenses`] order.
    license_rows: Vec<Entity>,
}

/// The clickable actions of this floater, carried on the pressed entity.
#[derive(Component, Clone, Copy)]
enum AboutAction {
    /// Copy the whole support block to the OS clipboard.
    CopyInfo,
    /// Show the license section with this [`AboutState::licenses`] index.
    SelectLicense(usize),
}

// ---------------------------------------------------------------------------
// Support-block assembly (pure, unit-tested).
// ---------------------------------------------------------------------------

/// The gathered inputs of [`support_block`] — every session-dependent field is
/// optional so the block renders sensibly before (or without) a login.
#[derive(Debug, Default, Clone, PartialEq)]
struct SupportInfo {
    /// The viewer name ([`build_info::VIEWER_NAME`]).
    viewer_name: String,
    /// The full viewer version ([`build_info::full_version`]).
    viewer_version: String,
    /// The build profile (`debug` / `release`).
    build_profile: String,
    /// The Bevy version from `Cargo.lock`, when embedded.
    bevy_version: Option<String>,
    /// The wgpu version from `Cargo.lock`, when embedded.
    wgpu_version: Option<String>,
    /// The login-derived session facts, absent without a session.
    session: Option<SessionFacts>,
    /// The current region's facts, absent until the region handshake.
    region: Option<RegionFacts>,
    /// The root simulator's UDP address.
    sim_host: Option<String>,
    /// The root simulator's version/channel string.
    simulator_version: Option<String>,
    /// The host system facts, absent until Bevy's `SystemInfo` exists.
    system: Option<SystemFacts>,
    /// The GPU facts from the wgpu adapter, absent in headless runs.
    gpu: Option<GpuFacts>,
    /// The primary window's physical size in pixels.
    window_size: Option<(u32, u32)>,
    /// The active UI language tag.
    ui_language: Option<String>,
}

/// The login-derived facts of [`SupportInfo`].
#[derive(Debug, Clone, PartialEq, Eq)]
struct SessionFacts {
    /// The grid directory name (`localhost`, `agni`, …).
    grid: String,
    /// The login URI.
    login_uri: String,
    /// The channel + version reported at login.
    channel: String,
}

/// The current-region facts of [`SupportInfo`].
#[derive(Debug, Clone, PartialEq, Eq)]
struct RegionFacts {
    /// The region name, when the grid sent one.
    name: Option<String>,
    /// The region's grid coordinates (region index pair).
    coordinates: (u32, u32),
    /// The raw `ProductName` (possibly empty, e.g. on OpenSim).
    product_name: String,
    /// The raw `ProductSKU` (possibly empty).
    product_sku: String,
}

/// The host-system facts of [`SupportInfo`] (from Bevy's `SystemInfo`).
#[derive(Debug, Clone, PartialEq, Eq)]
struct SystemFacts {
    /// The OS name and version.
    os: String,
    /// The kernel version.
    kernel: String,
    /// The CPU model name.
    cpu: String,
    /// The logical core count.
    core_count: String,
    /// The total memory.
    memory: String,
}

/// The GPU facts of [`SupportInfo`] (from the wgpu adapter).
#[derive(Debug, Clone, PartialEq, Eq)]
struct GpuFacts {
    /// The adapter (GPU) name.
    name: String,
    /// The adapter's device type (`DiscreteGpu`, `IntegratedGpu`, …).
    device_type: String,
    /// The graphics backend (`Vulkan`, `Metal`, …).
    backend: String,
    /// The driver name.
    driver: String,
    /// The driver version/info string.
    driver_info: String,
}

/// Renders the support block — the exact text the Info tab shows and the Copy
/// button puts on the clipboard. English labels by design (see module docs);
/// absent facts render as [`NOT_CONNECTED`] (session group) or are omitted
/// (optional lines), with stable line order and no trailing whitespace.
fn support_block(info: &SupportInfo) -> String {
    let mut block = String::new();
    let mut line = |text: String| {
        block.push_str(&text);
        block.push('\n');
    };

    line(format!(
        "{} {} ({} build)",
        info.viewer_name, info.viewer_version, info.build_profile
    ));
    match (&info.bevy_version, &info.wgpu_version) {
        (Some(bevy), Some(wgpu)) => line(format!("Bevy {bevy}, wgpu {wgpu}")),
        (Some(bevy), None) => line(format!("Bevy {bevy}")),
        (None, Some(wgpu)) => line(format!("wgpu {wgpu}")),
        (None, None) => {}
    }
    line(String::new());

    match &info.session {
        Some(session) => {
            line(format!("Grid: {} ({})", session.grid, session.login_uri));
            line(format!("Login channel: {}", session.channel));
        }
        None => line(format!("Grid: {NOT_CONNECTED}")),
    }
    if let Some(region) = &info.region {
        let name = region.name.as_deref().unwrap_or("(unnamed region)");
        let (x, y) = region.coordinates;
        line(format!("Region: {name} ({x}, {y})"));
        if !region.product_name.is_empty() || !region.product_sku.is_empty() {
            line(format!(
                "Product: {} ({})",
                region.product_name, region.product_sku
            ));
        }
    }
    if let Some(host) = &info.sim_host {
        line(format!("Simulator host: {host}"));
    }
    if let Some(version) = &info.simulator_version {
        line(format!("Simulator version: {version}"));
    }
    line(String::new());

    if let Some(system) = &info.system {
        line(format!("OS: {}", system.os));
        line(format!("Kernel: {}", system.kernel));
        line(format!("CPU: {} ({} cores)", system.cpu, system.core_count));
        line(format!("Memory: {}", system.memory));
    }
    if let Some(gpu) = &info.gpu {
        line(format!("GPU: {} ({})", gpu.name, gpu.device_type));
        line(format!("GPU driver: {} {}", gpu.driver, gpu.driver_info));
        line(format!("Graphics backend: {}", gpu.backend));
    }
    if let Some((width, height)) = info.window_size {
        line(format!("Window size: {width}x{height}"));
    }
    if let Some(language) = &info.ui_language {
        line(format!("UI language: {language}"));
    }

    block.trim_end().to_owned()
}

// ---------------------------------------------------------------------------
// License-file parsing (pure, unit-tested).
// ---------------------------------------------------------------------------

/// The marker prefix of a section header line in the generated license file.
const LICENSE_MARKER_PREFIX: &str = "=== LICENSE ";

/// The marker suffix of a section header line.
const LICENSE_MARKER_SUFFIX: &str = " ===";

/// The separator between the id and name in a section header line.
const LICENSE_MARKER_SEPARATOR: &str = " === ";

/// Parses the generated third-party license file: sections start at
/// `=== LICENSE <id> === <name> ===` lines, followed by a `used-by:` line and
/// the verbatim license text until the next marker. Content before the first
/// marker (the generated-file preamble) is skipped.
fn parse_license_sections(text: &str) -> Vec<LicenseSection> {
    let mut sections: Vec<LicenseSection> = Vec::new();
    for line in text.lines() {
        if let Some(header) = line
            .strip_prefix(LICENSE_MARKER_PREFIX)
            .and_then(|rest| rest.strip_suffix(LICENSE_MARKER_SUFFIX))
        {
            let (id, name) = match header.split_once(LICENSE_MARKER_SEPARATOR) {
                Some((id, name)) => (id.to_owned(), name.to_owned()),
                None => (header.to_owned(), header.to_owned()),
            };
            sections.push(LicenseSection {
                id,
                name,
                used_by: String::new(),
                text: String::new(),
            });
            continue;
        }
        let Some(current) = sections.last_mut() else {
            continue;
        };
        if current.text.is_empty()
            && current.used_by.is_empty()
            && let Some(used_by) = line.strip_prefix("used-by:")
        {
            used_by.trim().clone_into(&mut current.used_by);
            continue;
        }
        current.text.push_str(line);
        current.text.push('\n');
    }
    for section in &mut sections {
        section.text = section.text.trim().to_owned();
    }
    sections
}

/// The full license list: the project's own license first, then the parsed
/// third-party sections.
fn all_license_sections() -> Vec<LicenseSection> {
    let mut sections = vec![LicenseSection {
        id: "LGPL-2.1-only".to_owned(),
        name: "sl-client (this viewer)".to_owned(),
        used_by: String::new(),
        text: PROJECT_LICENSE.trim().to_owned(),
    }];
    sections.extend(parse_license_sections(THIRD_PARTY_LICENSES));
    sections
}

// ---------------------------------------------------------------------------
// Plugin, spawn, content build.
// ---------------------------------------------------------------------------

/// Registers the About floater: hidden chrome at startup, content on first
/// open, session-fact tracking and view refresh.
pub(crate) struct AboutFloaterPlugin;

impl Plugin for AboutFloaterPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<AboutState>()
            .add_systems(
                Startup,
                spawn_about_floater.after(UiScaffoldSystems::SpawnRoot),
            )
            .add_systems(
                Update,
                (
                    track_session_events,
                    (refresh_support_block, refresh_license_pane)
                        .run_if(floater_shown(ABOUT_FLOATER_ID)),
                ),
            );
    }
}

/// Spawn the (hidden) About floater's chrome; the tabs are built once, on the
/// first open ([`DeferredFloaterContent`]).
fn spawn_about_floater(mut commands: Commands, root: Res<UiRoot>) {
    let handle = spawn_floater(
        &mut commands,
        root.0,
        FloaterSpec {
            id: ABOUT_FLOATER_ID,
            title: "About".to_owned(),
            position: Vec2::new(300.0, 120.0),
            default_size: Some(Vec2::new(560.0, 480.0)),
            min_size: Some(Vec2::new(420.0, 320.0)),
            dock_host: None,
            caps: FloaterCaps {
                resizable: true,
                minimizable: false,
                closable: true,
                dockable: false,
            },
        },
    );
    commands
        .entity(handle.title_text)
        .insert(Translated::new("about-title"));
    let builder = commands.register_system(build_about_content);
    commands
        .entity(handle.root)
        .insert(DeferredFloaterContent { builder, handle });
}

/// First-open content build: the Info / Credits / Licenses tab container,
/// ending with the [`AboutUi`] insert (whose appearance wakes the refresh
/// systems) and the parsed license list in [`AboutState`].
fn build_about_content(
    In(handle): In<FloaterHandle>,
    mut commands: Commands,
    mut state: ResMut<AboutState>,
) {
    let labels: Vec<String> = ["about-tab-info", "about-tab-credits", "about-tab-licenses"]
        .into_iter()
        .map(str::to_owned)
        .collect();
    let tabs = spawn_tab_container(
        &mut commands,
        handle.content,
        &TabSpec {
            element: "about-tabs",
            placement: TabPlacement::BlockStart,
            labels: &labels,
            active: 0,
            tab_index: 1,
            font_size: FONT,
            strip_width: None,
            ellipsis: DEFAULT_ELLIPSIS,
            translate_labels: true,
        },
    );
    fill_tab_container(&mut commands, TabPlacement::BlockStart, &tabs);

    state.licenses = all_license_sections();
    state.selected_license = 0;
    state.rendered_license = None;
    state.rendered_block = String::new();

    let mut panels = tabs.panels.iter().copied();
    let support_text = panels
        .next()
        .map(|panel| build_info_tab(&mut commands, panel));
    if let Some(panel) = panels.next() {
        build_credits_tab(&mut commands, panel);
    }
    let license_ui = panels
        .next()
        .map(|panel| build_licenses_tab(&mut commands, panel, &state.licenses));

    if let (Some(support_text), Some((license_text, license_rows))) = (support_text, license_ui) {
        commands.insert_resource(AboutUi {
            support_text,
            license_text,
            license_rows,
        });
    }
}

/// A scrollable column (with a visible vertical scrollbar) filling `parent`,
/// returning the scrolling content column.
fn spawn_scroll_column(commands: &mut Commands, parent: Entity, name: &'static str) -> Entity {
    let scroll_row = commands
        .spawn((
            Node {
                width: Val::Percent(100.0),
                flex_grow: 1.0,
                min_height: Val::Px(0.0),
                align_items: AlignItems::Stretch,
                ..row(Val::Px(0.0))
            },
            Name::new(format!("{name}:scroll-row")),
            ChildOf(parent),
        ))
        .id();
    let content = commands
        .spawn((
            Node {
                flex_grow: 1.0,
                min_width: Val::Px(0.0),
                min_height: Val::Px(0.0),
                overflow: Overflow::scroll_y(),
                ..column(Val::Px(4.0))
            },
            BackgroundColor(Color::srgba(0.0, 0.0, 0.0, 0.20)),
            ScrollPosition::default(),
            crate::ui_tab::TabViewport { vertical: true },
            Name::new(format!("{name}:content")),
            ChildOf(scroll_row),
        ))
        .id();
    commands
        .spawn((
            Scrollbar {
                target: content,
                orientation: ControlOrientation::Vertical,
                min_thumb_length: SCROLLBAR_MIN_THUMB,
            },
            Node {
                width: Val::Px(SCROLLBAR_THICKNESS),
                flex_shrink: 0.0,
                ..default()
            },
            BackgroundColor(SCROLLBAR_TRACK_COLOR),
            Name::new(format!("{name}:scrollbar")),
            ChildOf(scroll_row),
        ))
        .with_child((
            ScrollbarThumb::default(),
            BackgroundColor(SCROLLBAR_THUMB_COLOR),
        ));
    content
}

/// Build the Info tab (intro, the support block, Copy to Clipboard), returning
/// the support block's `Text` entity.
fn build_info_tab(commands: &mut Commands, panel: Entity) -> Entity {
    let tab = commands
        .spawn((
            Node {
                width: Val::Percent(100.0),
                height: Val::Percent(100.0),
                min_height: Val::Px(0.0),
                ..column(Val::Px(8.0))
            },
            Name::new("about:info"),
            ChildOf(panel),
        ))
        .id();
    commands.spawn((
        Text::default(),
        Translated::new("about-intro"),
        UiFont::Sans.at(FONT),
        TextColor(LABEL_COLOR),
        Name::new("about:info:intro"),
        ChildOf(tab),
    ));
    let scroll = spawn_scroll_column(commands, tab, "about:info");
    let support_text = commands
        .spawn((
            Text::default(),
            UiFont::Mono.at(MONO_FONT),
            TextColor(LABEL_COLOR),
            Name::new("about:info:support-block"),
            ChildOf(scroll),
        ))
        .id();
    let footer = commands
        .spawn((
            Node {
                justify_content: JustifyContent::FlexEnd,
                flex_shrink: 0.0,
                ..row(Val::Px(8.0))
            },
            Name::new("about:info:footer"),
            ChildOf(tab),
        ))
        .id();
    spawn_about_button(commands, footer, "about-copy", AboutAction::CopyInfo, 2);
    support_text
}

/// Build the Credits tab: translated acknowledgement paragraphs.
fn build_credits_tab(commands: &mut Commands, panel: Entity) {
    let tab = commands
        .spawn((
            Node {
                width: Val::Percent(100.0),
                height: Val::Percent(100.0),
                min_height: Val::Px(0.0),
                ..column(Val::Px(8.0))
            },
            Name::new("about:credits"),
            ChildOf(panel),
        ))
        .id();
    let scroll = spawn_scroll_column(commands, tab, "about:credits");
    for key in [
        "about-credits-intro",
        "about-credits-protocol",
        "about-credits-reference",
        "about-credits-engine",
    ] {
        commands.spawn((
            Text::default(),
            Translated::new(key),
            UiFont::Sans.at(FONT),
            TextColor(LABEL_COLOR),
            Name::new(format!("about:credits:{key}")),
            ChildOf(scroll),
        ));
    }
}

/// Build the Licenses tab: a two-pane browser — the license list on the
/// leading side, the selected section's text trailing — returning the text
/// pane's `Text` entity and the list rows in section order.
fn build_licenses_tab(
    commands: &mut Commands,
    panel: Entity,
    licenses: &[LicenseSection],
) -> (Entity, Vec<Entity>) {
    let tab = commands
        .spawn((
            Node {
                width: Val::Percent(100.0),
                height: Val::Percent(100.0),
                min_height: Val::Px(0.0),
                align_items: AlignItems::Stretch,
                ..row(Val::Px(8.0))
            },
            Name::new("about:licenses"),
            ChildOf(panel),
        ))
        .id();

    let list_holder = commands
        .spawn((
            Node {
                width: Val::Px(LICENSE_LIST_WIDTH),
                flex_shrink: 0.0,
                min_height: Val::Px(0.0),
                ..column(Val::Px(0.0))
            },
            Name::new("about:licenses:list-holder"),
            ChildOf(tab),
        ))
        .id();
    let list = spawn_scroll_column(commands, list_holder, "about:licenses:list");
    let mut rows = Vec::with_capacity(licenses.len());
    for (index, section) in licenses.iter().enumerate() {
        let row_entity = commands
            .spawn((
                Button,
                AboutAction::SelectLicense(index),
                TabIndex(3),
                Node {
                    width: Val::Percent(100.0),
                    padding: UiRect::axes(Val::Px(6.0), Val::Px(3.0)),
                    ..row(Val::Px(4.0))
                },
                BackgroundColor(LICENSE_ROW_UNSELECTED),
                Pickable::default(),
                Name::new(format!("about:licenses:row:{}", section.id)),
                ChildOf(list),
            ))
            .observe(on_about_action)
            .id();
        // Many sections share one SPDX id (each crate's MIT text differs by
        // its copyright line), so the first using crate is what tells the
        // rows apart.
        let label = match section.used_by.split(',').next().map(str::trim) {
            Some(first_crate) if !first_crate.is_empty() => {
                format!("{}: {first_crate}", section.id)
            }
            _ => format!("{} ({})", section.id, section.name),
        };
        commands.spawn((
            Text::new(label),
            UiFont::Sans.at(FONT),
            TextColor(LABEL_COLOR),
            Pickable::IGNORE,
            ChildOf(row_entity),
        ));
        rows.push(row_entity);
    }

    let text_holder = commands
        .spawn((
            Node {
                flex_grow: 1.0,
                min_width: Val::Px(0.0),
                min_height: Val::Px(0.0),
                ..column(Val::Px(0.0))
            },
            Name::new("about:licenses:text-holder"),
            ChildOf(tab),
        ))
        .id();
    let text_scroll = spawn_scroll_column(commands, text_holder, "about:licenses:text");
    let license_text = commands
        .spawn((
            Text::default(),
            UiFont::Mono.at(MONO_FONT),
            TextColor(LABEL_COLOR),
            Name::new("about:licenses:text"),
            ChildOf(text_scroll),
        ))
        .id();
    (license_text, rows)
}

/// Spawn a translated-label action button carrying an [`AboutAction`].
fn spawn_about_button(
    commands: &mut Commands,
    parent: Entity,
    label_key: &'static str,
    action: AboutAction,
    tab_index: i32,
) -> Entity {
    let button = commands
        .spawn((
            Button,
            TabIndex(tab_index),
            action,
            Node {
                padding: UiRect::axes(Val::Px(14.0), Val::Px(5.0)),
                border: UiRect::all(Val::Px(2.0)),
                ..default()
            },
            BorderColor::all(CONTROL_BORDER),
            BackgroundColor(BUTTON_BACKGROUND),
            Pickable::default(),
            Name::new(format!("about:button:{label_key}")),
            ChildOf(parent),
        ))
        .observe(on_about_action)
        .id();
    commands.spawn((
        Text::default(),
        Translated::new(label_key),
        UiFont::Sans.at(FONT),
        TextColor(LABEL_COLOR),
        Pickable::IGNORE,
        ChildOf(button),
    ));
    button
}

// ---------------------------------------------------------------------------
// Systems.
// ---------------------------------------------------------------------------

/// Track the session facts the support block needs — **unconditional** (not
/// gated on the floater being open), since the login-time events fire long
/// before the floater's first open and must not be missed.
fn track_session_events(mut events: MessageReader<SlEvent>, mut state: ResMut<AboutState>) {
    for event in events.read() {
        match &event.0 {
            SlSessionEvent::SimulatorVersion(version) => {
                state.simulator_version = Some(version.clone());
            }
            SlSessionEvent::CircuitEstablished { sim, .. } => {
                state.sim_host = Some(*sim);
            }
            SlSessionEvent::RegionChanged { sim, .. } => {
                // The destination's own `SimulatorVersion` follows in the same
                // event batch; clearing first keeps a stale source value from
                // surviving a handover that (unexpectedly) sends none.
                state.sim_host = Some(*sim);
                state.simulator_version = None;
            }
            _ => {}
        }
    }
}

/// Re-render the support block while the floater is open, writing the `Text`
/// only when the assembled string changed (build-once / update-in-place).
#[expect(
    clippy::too_many_arguments,
    reason = "a Bevy system's parameters are its injected resources / queries: the model \
              state, the built UI handles, the login facts, the region query, the host / \
              GPU / window / locale sources, and the text sink"
)]
fn refresh_support_block(
    mut state: ResMut<AboutState>,
    ui: Option<Res<AboutUi>>,
    session: Option<Res<AboutSessionInfo>>,
    regions: Query<&SlRegionIdentity, With<SlCurrentRegion>>,
    system_info: Option<Res<SystemInfo>>,
    adapter: Option<Res<RenderAdapterInfo>>,
    windows: Query<&Window, With<bevy::window::PrimaryWindow>>,
    locale: Res<UiLocale>,
    mut texts: Query<&mut Text>,
) {
    let Some(ui) = ui else {
        return;
    };
    let info = SupportInfo {
        viewer_name: build_info::VIEWER_NAME.to_owned(),
        viewer_version: build_info::full_version(),
        build_profile: build_info::BUILD_PROFILE.to_owned(),
        bevy_version: build_info::BEVY_VERSION.map(str::to_owned),
        wgpu_version: build_info::WGPU_VERSION.map(str::to_owned),
        session: session.map(|session| SessionFacts {
            grid: session.grid.clone(),
            login_uri: session.login_uri.clone(),
            channel: format!("{} {}", session.channel, session.version),
        }),
        region: regions.iter().next().map(|identity| RegionFacts {
            name: identity.0.sim_name.as_ref().map(ToString::to_string),
            coordinates: (
                identity.0.grid_coordinates.x(),
                identity.0.grid_coordinates.y(),
            ),
            product_name: identity.0.product_name.clone(),
            product_sku: identity.0.product_sku.clone(),
        }),
        sim_host: state.sim_host.map(|host| host.to_string()),
        simulator_version: state.simulator_version.clone(),
        system: system_info.map(|system| SystemFacts {
            os: system.os.clone(),
            kernel: system.kernel.clone(),
            cpu: system.cpu.clone(),
            core_count: system.core_count.clone(),
            memory: system.memory.clone(),
        }),
        gpu: adapter.map(|adapter| GpuFacts {
            name: adapter.name.clone(),
            device_type: format!("{:?}", adapter.device_type),
            backend: adapter.backend.to_string(),
            driver: adapter.driver.clone(),
            driver_info: adapter.driver_info.clone(),
        }),
        window_size: windows
            .iter()
            .next()
            .map(|window| (window.physical_width(), window.physical_height())),
        ui_language: Some(locale.lang.to_string()),
    };
    let block = support_block(&info);
    if block != state.rendered_block {
        if let Ok(mut text) = texts.get_mut(ui.support_text) {
            *text = Text::new(block.clone());
        }
        state.rendered_block = block;
    }
}

/// Render the selected license into the text pane (and move the row
/// highlight) when the selection changes.
fn refresh_license_pane(
    mut state: ResMut<AboutState>,
    ui: Option<Res<AboutUi>>,
    mut texts: Query<&mut Text>,
    mut backgrounds: Query<&mut BackgroundColor>,
) {
    let Some(ui) = ui else {
        return;
    };
    let selected = state.selected_license;
    if state.rendered_license == Some(selected) {
        return;
    }
    let Some(section) = state.licenses.get(selected) else {
        return;
    };
    let content = if section.used_by.is_empty() {
        section.text.clone()
    } else {
        format!("Used by: {}\n\n{}", section.used_by, section.text)
    };
    if let Ok(mut text) = texts.get_mut(ui.license_text) {
        *text = Text::new(content);
    }
    for (index, row_entity) in ui.license_rows.iter().enumerate() {
        if let Ok(mut background) = backgrounds.get_mut(*row_entity) {
            background.0 = if index == selected {
                LICENSE_ROW_SELECTED
            } else {
                LICENSE_ROW_UNSELECTED
            };
        }
    }
    state.rendered_license = Some(selected);
}

/// The shared press observer of this floater's actions: Copy puts the current
/// support block on the OS clipboard; a license row selects its section.
fn on_about_action(
    press: On<Pointer<Press>>,
    actions: Query<&AboutAction>,
    clipboard: Res<ViewerClipboard>,
    mut state: ResMut<AboutState>,
) {
    if press.button != PointerButton::Primary {
        return;
    }
    let Ok(action) = actions.get(press.entity) else {
        return;
    };
    match action {
        AboutAction::CopyInfo => copy_to_clipboard(&clipboard, &state.rendered_block),
        AboutAction::SelectLicense(index) => state.selected_license = *index,
    }
}

// ---------------------------------------------------------------------------
// Tests.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use pretty_assertions::assert_eq;

    use super::{
        GpuFacts, LicenseSection, RegionFacts, SessionFacts, SupportInfo, SystemFacts,
        parse_license_sections, support_block,
    };

    /// A fully-populated info renders every group in stable order.
    #[test]
    fn support_block_full() {
        let info = SupportInfo {
            viewer_name: "sl-client-bevy-viewer".to_owned(),
            viewer_version: "0.1.0+abc1234".to_owned(),
            build_profile: "release".to_owned(),
            bevy_version: Some("0.19.0".to_owned()),
            wgpu_version: Some("26.0.1".to_owned()),
            session: Some(SessionFacts {
                grid: "localhost".to_owned(),
                login_uri: "http://127.0.0.1:9000/".to_owned(),
                channel: "sl-client-bevy-viewer 0.1.0+abc1234".to_owned(),
            }),
            region: Some(RegionFacts {
                name: Some("Default Region".to_owned()),
                coordinates: (1000, 1000),
                product_name: "Mainland".to_owned(),
                product_sku: "023".to_owned(),
            }),
            sim_host: Some("127.0.0.1:9001".to_owned()),
            simulator_version: Some("OpenSim 0.9.3.1 Yeti Dev".to_owned()),
            system: Some(SystemFacts {
                os: "Gentoo Linux".to_owned(),
                kernel: "6.12.1".to_owned(),
                cpu: "AMD Ryzen 9".to_owned(),
                core_count: "32".to_owned(),
                memory: "64.0 GiB".to_owned(),
            }),
            gpu: Some(GpuFacts {
                name: "AMD Radeon RX 7900 XTX".to_owned(),
                device_type: "DiscreteGpu".to_owned(),
                backend: "Vulkan".to_owned(),
                driver: "radv".to_owned(),
                driver_info: "Mesa 25.0.1".to_owned(),
            }),
            window_size: Some((2560, 1440)),
            ui_language: Some("en".to_owned()),
        };
        assert_eq!(
            support_block(&info),
            "sl-client-bevy-viewer 0.1.0+abc1234 (release build)\n\
             Bevy 0.19.0, wgpu 26.0.1\n\
             \n\
             Grid: localhost (http://127.0.0.1:9000/)\n\
             Login channel: sl-client-bevy-viewer 0.1.0+abc1234\n\
             Region: Default Region (1000, 1000)\n\
             Product: Mainland (023)\n\
             Simulator host: 127.0.0.1:9001\n\
             Simulator version: OpenSim 0.9.3.1 Yeti Dev\n\
             \n\
             OS: Gentoo Linux\n\
             Kernel: 6.12.1\n\
             CPU: AMD Ryzen 9 (32 cores)\n\
             Memory: 64.0 GiB\n\
             GPU: AMD Radeon RX 7900 XTX (DiscreteGpu)\n\
             GPU driver: radv Mesa 25.0.1\n\
             Graphics backend: Vulkan\n\
             Window size: 2560x1440\n\
             UI language: en"
        );
    }

    /// With nothing session-derived available the block still renders — the
    /// grid line says not connected, optional lines are omitted, and there is
    /// no trailing whitespace.
    #[test]
    fn support_block_not_connected() {
        let info = SupportInfo {
            viewer_name: "sl-client-bevy-viewer".to_owned(),
            viewer_version: "0.1.0".to_owned(),
            build_profile: "debug".to_owned(),
            ..SupportInfo::default()
        };
        let block = support_block(&info);
        assert_eq!(
            block,
            "sl-client-bevy-viewer 0.1.0 (debug build)\n\
             \n\
             Grid: (not connected)"
        );
        assert!(
            block.lines().all(|line| line.trim_end() == line),
            "no line may carry trailing whitespace: {block:?}"
        );
    }

    /// The generated-file format round-trips: preamble skipped, id / name /
    /// used-by / text captured per section.
    #[test]
    fn parse_license_sections_sample() {
        let sample = "Third-party licenses.\n\
                      Generated file preamble.\n\
                      \n\
                      === LICENSE Apache-2.0 === Apache License 2.0 ===\n\
                      used-by: foo 1.0.0, bar 2.1.3\n\
                      \n\
                      Apache License\n\
                      Version 2.0, January 2004\n\
                      \n\
                      === LICENSE MIT === MIT License ===\n\
                      used-by: baz 0.3.0\n\
                      \n\
                      MIT License text.\n";
        assert_eq!(
            parse_license_sections(sample),
            vec![
                LicenseSection {
                    id: "Apache-2.0".to_owned(),
                    name: "Apache License 2.0".to_owned(),
                    used_by: "foo 1.0.0, bar 2.1.3".to_owned(),
                    text: "Apache License\nVersion 2.0, January 2004".to_owned(),
                },
                LicenseSection {
                    id: "MIT".to_owned(),
                    name: "MIT License".to_owned(),
                    used_by: "baz 0.3.0".to_owned(),
                    text: "MIT License text.".to_owned(),
                },
            ]
        );
    }
}
