//! Appearance & wearables (viewer-notification-catalogue-appearance-wearables).
//!
//! Outfit / wearable editing confirms and failures, raised by the
//! appearance / outfits features (data entries only; the owning
//! feature raises each and reads the response).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    DISCARD_KEEP_EDITING_FORM, NO_FORM, NotificationIgnore, NotificationInput, NotificationKind,
    NotificationPriority, NotificationTemplate, OK_CANCEL_FORM, OK_FORM, REPLACE_ATTACHMENT_FORM,
    SAVE_ALL_DISCARD_CANCEL_FORM, SAVE_CANCEL_FORM, SAVE_DISCARD_CANCEL_FORM, YES_NO_FORM,
};

/// The appearance & wearables family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "WearableSave",
        kind: NotificationKind::AlertModal,
        message_key: "notification-wearable-save",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: SAVE_DISCARD_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SaveClothingBodyChanges",
        kind: NotificationKind::AlertModal,
        message_key: "notification-save-clothing-body-changes",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: SAVE_ALL_DISCARD_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UsavedWearableChanges",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unsaved-wearable-changes",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-usaved-wearable-changes"),
        form: DISCARD_KEEP_EDITING_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutoWearNewClothing",
        kind: NotificationKind::AlertModal,
        message_key: "notification-auto-wear-new-clothing",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-auto-wear-new-clothing"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SaveWearableAs",
        kind: NotificationKind::AlertModal,
        message_key: "notification-save-wearable-as",
        title_key: Some("notification-title-save-wearable"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: Some("notification-save-wearable-as-default"),
        }),
    },
    NotificationTemplate {
        name: "SaveOutfitAs",
        kind: NotificationKind::AlertModal,
        message_key: "notification-save-outfit-as",
        title_key: Some("notification-title-save-outfit"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: Some("notification-save-outfit-as-default"),
        }),
    },
    NotificationTemplate {
        name: "RenameOutfit",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rename-outfit",
        title_key: Some("notification-title-rename-outfit"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "new_name",
            default_key: Some("notification-rename-outfit-default"),
        }),
    },
    NotificationTemplate {
        name: "ConfirmOverwriteOutfit",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-overwrite-outfit",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-overwrite-outfit"),
        form: SAVE_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DeleteOutfits",
        kind: NotificationKind::AlertModal,
        message_key: "notification-delete-outfits",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DeleteOutfitsWithName",
        kind: NotificationKind::AlertModal,
        message_key: "notification-delete-outfits-with-name",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDeleteRequiredClothing",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cant-delete-required-clothing",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MyOutfitsPasteFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-my-outfits-paste-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CouldNotPutOnOutfit",
        kind: NotificationKind::AlertModal,
        message_key: "notification-could-not-put-on-outfit",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotWearTrash",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-wear-trash",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotWearInfoNotComplete",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-wear-info-not-complete",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CanNotChangeAppearanceUntilLoaded",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-change-appearance-until-loaded",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ClothingLoading",
        kind: NotificationKind::AlertModal,
        message_key: "notification-clothing-loading",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-clothing-loading"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TooManyWearables",
        kind: NotificationKind::AlertModal,
        message_key: "notification-too-many-wearables",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MaxAttachmentsOnOutfit",
        kind: NotificationKind::AlertModal,
        message_key: "notification-max-attachments-on-outfit",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotSaveWearableOutOfSpace",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-save-wearable-out-of-space",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotSaveToAssetStore",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-save-to-asset-store",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ThumbnailOutfitPhoto",
        kind: NotificationKind::AlertModal,
        message_key: "notification-thumbnail-outfit-photo",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutfitPhotoLoadError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outfit-photo-load-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FSLargeOutfitsWarningInThisSession",
        kind: NotificationKind::AlertModal,
        message_key: "notification-large-outfits-warning",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-fs-large-outfits-warning-in-this-session"),
        form: OK_FORM,
        input: None,
    },
    // Attachment prompts. `ReplaceAttachment`'s reference `save_option`
    // (remember my choice) is approximated by the plain suppress flag: a
    // suppressed raise shows nothing, rather than replaying the saved
    // answer (the `ConfirmQuit` precedent).
    NotificationTemplate {
        name: "AttachmentDrop",
        kind: NotificationKind::AlertModal,
        message_key: "notification-attachment-drop",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-attachment-drop"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ReplaceAttachment",
        kind: NotificationKind::Alert,
        message_key: "notification-replace-attachment",
        title_key: Some("notification-title-replace-existing-attachment"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::LastResponse,
        ignore_key: Some("notification-ignoretext-replace-attachment"),
        form: REPLACE_ATTACHMENT_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RiggedMeshAttachedToHUD",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rigged-mesh-attached-to-hud",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-rigged-mesh-attached-to-hud"),
        form: OK_FORM,
        input: None,
    },
    // Appearance tips / notifies, including the avatar-rez diagnostic
    // family (the reference's cloud / bake progress reporting).
    NotificationTemplate {
        name: "CancelledAttach",
        kind: NotificationKind::Tip,
        message_key: "notification-cancelled-attach",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ReplacedMissingWearable",
        kind: NotificationKind::Tip,
        message_key: "notification-replaced-missing-wearable",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AttachmentSaved",
        kind: NotificationKind::Tip,
        message_key: "notification-attachment-saved",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FailedToFindWearable",
        kind: NotificationKind::Notify,
        message_key: "notification-failed-to-find-wearable-named",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidWearable",
        kind: NotificationKind::Notify,
        message_key: "notification-invalid-wearable",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AppearanceToXMLSaved",
        kind: NotificationKind::Notify,
        message_key: "notification-appearance-to-xml-saved",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AppearanceToXMLFailed",
        kind: NotificationKind::Tip,
        message_key: "notification-appearance-to-xml-failed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ShapeImportGenericFail",
        kind: NotificationKind::Tip,
        message_key: "notification-shape-import-generic-fail",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ShapeImportVersionFail",
        kind: NotificationKind::Tip,
        message_key: "notification-shape-import-version-fail",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezSelfBakedDoneNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-self-baked-done",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezSelfBakedUpdateNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-self-baked-update",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezSelfBakeForceUpdateNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-self-bake-force-update",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezCloudNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-cloud",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezArrivedNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-arrived",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezLeftCloudNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-left-cloud",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezEnteredAppearanceNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-entered-appearance",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezLeftAppearanceNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-left-appearance",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezLeftNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-left",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezSelfBakedTextureUploadNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-self-baked-texture-upload",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AvatarRezSelfBakedTextureUpdateNotification",
        kind: NotificationKind::Tip,
        message_key: "notification-avatar-rez-self-baked-texture-update",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // Server-keyed attach / drop refusals: the simulator sends these by
    // `AlertInfo` key, so `ingest_alert_messages` resolves them from the
    // catalogue automatically.
    NotificationTemplate {
        name: "NotEnoughResourcesToAttach",
        kind: NotificationKind::Notify,
        message_key: "notification-not-enough-resources-to-attach",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AttachmentHasTooMuchInventory",
        kind: NotificationKind::Notify,
        message_key: "notification-attachment-has-too-much-inventory",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "IllegalAttachment",
        kind: NotificationKind::Notify,
        message_key: "notification-illegal-attachment",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttackMultipleObjOneSpot",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-multiple-obj-one-spot",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoPermsTooManyAttachedAnimatedObjects",
        kind: NotificationKind::Notify,
        message_key: "notification-no-perms-too-many-attached-animated-objects",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachObjectAvatarSittingOnIt",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-object-avatar-sitting-on-it",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WhyAreYouTryingToWearShrubbery",
        kind: NotificationKind::Notify,
        message_key: "notification-why-are-you-trying-to-wear-shrubbery",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachGroupOwnedObjs",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-group-owned-objs",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachObjectsNotOwned",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-objects-not-owned",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachNavmeshObjects",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-navmesh-objects",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachObjectNoMovePermissions",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-object-no-move-permissions",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachNotEnoughScriptResources",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-not-enough-script-resources",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAttachObjectBeingRemoved",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-attach-object-being-removed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropItemTrialUser",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-item-trial-user",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropMeshAttachment",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-mesh-attachment",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropAttachmentNoPermission",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-attachment-no-permission",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropAttachmentInsufficientLandResources",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-attachment-insufficient-land-resources",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropAttachmentInsufficientResources",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-attachment-insufficient-resources",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantDropObjectFullParcel",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-drop-object-full-parcel",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantCreateOutfit",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-create-outfit",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
