//! Avatar movement (viewer-notification-catalogue-avatar-movement).
//!
//! Animation-upload failures and the animation-overrider (AO) set
//! management prompts, raised by the animation / AO features.
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationInput, NotificationKind, NotificationPriority,
    NotificationTemplate, OK_CANCEL_FORM, OK_FORM, REMOVE_CANCEL_FORM,
};

/// The avatar movement family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "WriteAnimationFail",
        kind: NotificationKind::AlertModal,
        message_key: "notification-write-animation-fail",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DoNotSupportBulkAnimationUpload",
        kind: NotificationKind::AlertModal,
        message_key: "notification-do-not-support-bulk-animation-upload",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NewAOSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-new-ao-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: Some("notification-new-ao-set-default"),
        }),
    },
    NotificationTemplate {
        name: "NewAOCantContainNonASCII",
        kind: NotificationKind::AlertModal,
        message_key: "notification-new-ao-cant-contain-non-ascii",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RenameAOMustBeASCII",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rename-ao-must-be-ascii",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NewAONameCantExist",
        kind: NotificationKind::AlertModal,
        message_key: "notification-new-ao-name-cant-exist",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RemoveAOSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-ao-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: REMOVE_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOForeignItemsFound",
        kind: NotificationKind::AlertModal,
        message_key: "notification-ao-foreign-items-found",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmPoserOverwrite",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-poser-overwrite",
        title_key: Some("notification-title-confirm-pose-overwrite"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    // Movement notifies: the scripted-control notice and the
    // server-keyed sit / stand refusals (`AlertInfo` keys, resolved by
    // `ingest_alert_messages` automatically).
    NotificationTemplate {
        name: "FirstOverrideKeys",
        kind: NotificationKind::Notify,
        message_key: "notification-first-override-keys",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SitFailCantMove",
        kind: NotificationKind::Notify,
        message_key: "notification-sit-fail-cant-move",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SitFailNotAllowedOnLand",
        kind: NotificationKind::Notify,
        message_key: "notification-sit-fail-not-allowed-on-land",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SitFailNotSameRegion",
        kind: NotificationKind::Notify,
        message_key: "notification-sit-fail-not-same-region",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StandDeniedByObject",
        kind: NotificationKind::Notify,
        message_key: "notification-stand-denied-by-object",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ResitDeniedByObject",
        kind: NotificationKind::Notify,
        message_key: "notification-resit-denied-by-object",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantSitNoSuitableSurface",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-sit-no-suitable-surface",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantSitNoRoom",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-sit-no-room",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // AO notecard-import progress tips and the movement-mode toggle
    // tips (phantom / movelock / flight assist).
    NotificationTemplate {
        name: "AOImportComplete",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-complete",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportSetAlreadyExists",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-set-already-exists",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportPermissionDenied",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-permission-denied",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportCreateSetFailed",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-create-set-failed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportDownloadFailed",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-download-failed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportNoText",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-no-text",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportNoFolder",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-no-folder",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportNoStatePrefix",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-no-state-prefix",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportNoValidDelimiter",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-no-valid-delimiter",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportStateNameNotFound",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-state-name-not-found",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportAnimationNotFound",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-animation-not-found",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportInvalid",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-invalid",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportRetryCreateSet",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-retry-create-set",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportAbortCreateSet",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-abort-create-set",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AOImportLinkFailed",
        kind: NotificationKind::Tip,
        message_key: "notification-ao-import-link-failed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PhantomOn",
        kind: NotificationKind::Tip,
        message_key: "notification-phantom-on",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PhantomOff",
        kind: NotificationKind::Tip,
        message_key: "notification-phantom-off",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MovelockEnabled",
        kind: NotificationKind::Tip,
        message_key: "notification-movelock-enabled",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MovelockDisabled",
        kind: NotificationKind::Tip,
        message_key: "notification-movelock-disabled",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MovelockEnabling",
        kind: NotificationKind::Tip,
        message_key: "notification-movelock-enabling",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MovelockDisabling",
        kind: NotificationKind::Tip,
        message_key: "notification-movelock-disabling",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FlightAssistEnabled",
        kind: NotificationKind::Tip,
        message_key: "notification-flight-assist-enabled",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
