//! Diagnostics (viewer-notification-catalogue-diagnostics).
//!
//! Installation / environment / hardware warnings and viewer-internal
//! errors. The hardware confirms (`UnsupportedHardware`,
//! `OldGPUDriver`) carry a visit-the-URL affirmative; the URL-opening
//! action belongs to the raising feature.
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM, SEND_CANCEL_FORM, YES_NO_BUTTONS_FORM, YES_NO_FORM,
};

/// The diagnostics family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "MissingAlert",
        kind: NotificationKind::Notify,
        message_key: "notification-missing-alert",
        title_key: Some("notification-title-unknown-notification-message"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FloaterNotFound",
        kind: NotificationKind::AlertModal,
        message_key: "notification-floater-not-found",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "BadInstallation",
        kind: NotificationKind::AlertModal,
        message_key: "notification-bad-installation",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FoundLegacyNsisInstallation",
        kind: NotificationKind::AlertModal,
        message_key: "notification-found-legacy-nsis-installation",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MessageTemplateNotFound",
        kind: NotificationKind::AlertModal,
        message_key: "notification-message-template-not-found",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AllowMultipleViewers",
        kind: NotificationKind::AlertModal,
        message_key: "notification-allow-multiple-viewers",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnsupportedHardware",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unsupported-hardware",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-unsupported-hardware"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OldGPUDriver",
        kind: NotificationKind::AlertModal,
        message_key: "notification-old-gpu-driver",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-old-gpu-driver"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnknownGPU",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unknown-gpu",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-unknown-gpu"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DisplaySettingsNoShaders",
        kind: NotificationKind::AlertModal,
        message_key: "notification-display-settings-no-shaders",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoHavok",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-havok",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-no-havok"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoSupportGLTFShader",
        kind: NotificationKind::Notify,
        message_key: "notification-no-support-gltf-shader",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LowMemory",
        kind: NotificationKind::AlertModal,
        message_key: "notification-low-memory",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ForceQuitDueToLowMemory",
        kind: NotificationKind::AlertModal,
        message_key: "notification-force-quit-due-to-low-memory",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutOfDiskSpace",
        kind: NotificationKind::Tip,
        message_key: "notification-out-of-disk-space",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RegionCapabilityRequestError",
        kind: NotificationKind::Alert,
        message_key: "notification-region-capability-request-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MissingString",
        kind: NotificationKind::AlertModal,
        message_key: "notification-missing-string",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FailedRequirementsCheck",
        kind: NotificationKind::AlertModal,
        message_key: "notification-failed-requirements-check",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CompressionTestResults",
        kind: NotificationKind::AlertModal,
        message_key: "notification-compression-test-results",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SendSysinfoToIM",
        kind: NotificationKind::AlertModal,
        message_key: "notification-send-sysinfo-to-im",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: SEND_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FireStormReqInfo",
        kind: NotificationKind::AlertModal,
        message_key: "notification-firestorm-req-info",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_BUTTONS_FORM,
        input: None,
    },
    // File-handling failures (upload / resource / generic file I/O).
    NotificationTemplate {
        name: "CannotWriteFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-write-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoFileExtension",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-file-extension",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidFileExtension",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-file-extension",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ProblemWithFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-problem-with-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotEncodeFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-encode-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CorruptResourceFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-corrupt-resource-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnknownResourceFileVersion",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unknown-resource-file-version",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnableToCreateOutputFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unable-to-create-output-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotUploadReason",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-upload-reason",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotOpenFileTooBig",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-open-file-too-big",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotLoad",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-load",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NotRegularFileError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-not-regular-file-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NotFolderError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-not-folder-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericFileEmptyError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-file-empty-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericFileOpenReadError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-file-open-read-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericFileOpenWriteError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-file-open-write-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericFileReadError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-file-read-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericFileWriteError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-file-write-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    // Local-file live-update failures (the local bitmaps / GLTF
    // preview watchers), persistent notifies in the reference.
    NotificationTemplate {
        name: "LocalBitmapsUpdateFileNotFound",
        kind: NotificationKind::Notify,
        message_key: "notification-local-bitmaps-update-file-not-found",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LocalBitmapsUpdateFailedFinal",
        kind: NotificationKind::Notify,
        message_key: "notification-local-bitmaps-update-failed-final",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LocalBitmapsVerifyFail",
        kind: NotificationKind::Notify,
        message_key: "notification-local-bitmaps-verify-fail",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LocalGLTFVerifyFail",
        kind: NotificationKind::Notify,
        message_key: "notification-local-gltf-verify-fail",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
