//! Experiences (viewer-notification-catalogue-experiences).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM,
};

/// The experiences family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "ExperienceAcquireFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-experience-acquire-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NotInGroupExperienceProfileMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-not-in-group-experience-profile-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UneditableExperienceProfileMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-uneditable-experience-profile-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RestrictedToOwnerExperienceProfileMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-restricted-to-owner-experience-profile-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MaturityRatingExceedsOwnerExperienceProfileMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-maturity-rating-exceeds-owner-experience-profile-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RestrictedTermExperienceProfileMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-restricted-term-experience-profile-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TeleportedHomeExperienceRemoved",
        kind: NotificationKind::Notify,
        message_key: "notification-teleported-home-experience-removed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-teleported-home-experience-removed"),
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TrustedExperienceEntry",
        kind: NotificationKind::Notify,
        message_key: "notification-trusted-experience-entry",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-trusted-experience-entry"),
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ExperienceEvent",
        kind: NotificationKind::Tip,
        message_key: "notification-experience-event",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ExperienceEventAttachment",
        kind: NotificationKind::Tip,
        message_key: "notification-experience-event-attachment",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
