//! Friends & people (viewer-notification-catalogue-friends-people).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    ACCEPT_DECLINE_FORM, CREATE_CANCEL_FORM, NO_FORM, NotificationIgnore, NotificationInput,
    NotificationKind, NotificationPriority, NotificationTemplate, OFFER_CANCEL_FORM,
    OK_CANCEL_FORM, OK_FORM, YES_NO_FORM,
};

/// The friends & people family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "GrantModifyRights",
        kind: NotificationKind::AlertModal,
        message_key: "notification-grant-modify-rights",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GrantModifyRightsMultiple",
        kind: NotificationKind::AlertModal,
        message_key: "notification-grant-modify-rights-multiple",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RevokeModifyRights",
        kind: NotificationKind::AlertModal,
        message_key: "notification-revoke-modify-rights",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RevokeModifyRightsMultiple",
        kind: NotificationKind::AlertModal,
        message_key: "notification-revoke-modify-rights-multiple",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MuteLimitReached",
        kind: NotificationKind::Notify,
        message_key: "notification-mute-limit-reached",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddFriendWithMessage",
        kind: NotificationKind::AlertModal,
        message_key: "notification-add-friend-with-message",
        title_key: Some("notification-title-add-friend"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OFFER_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: Some("notification-add-friend-with-message-default"),
        }),
    },
    NotificationTemplate {
        name: "RemoveMultipleFromFriends",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-multiple-from-friends",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RevokedModifyRights",
        kind: NotificationKind::Notify,
        message_key: "notification-revoked-modify-rights",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MuteLinden",
        kind: NotificationKind::AlertModal,
        message_key: "notification-mute-linden",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MuteByNameFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-mute-by-name-failed",
        title_key: Some("notification-title-block-object-by-name-failed"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantOfferCallingCard",
        kind: NotificationKind::Alert,
        message_key: "notification-cant-offer-calling-card",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantOfferFriendship",
        kind: NotificationKind::Alert,
        message_key: "notification-cant-offer-friendship",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RejectFriendshipRequestsModeSet",
        kind: NotificationKind::Alert,
        message_key: "notification-reject-friendship-requests-mode-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-reject-friendship-requests-mode-set"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendOnlineOffline",
        kind: NotificationKind::Tip,
        message_key: "notification-friend-online-offline",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddSelfFriend",
        kind: NotificationKind::Tip,
        message_key: "notification-add-self-friend",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddSelfRenderExceptions",
        kind: NotificationKind::Tip,
        message_key: "notification-add-self-render-exceptions",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OfferedCard",
        kind: NotificationKind::Tip,
        message_key: "notification-offered-card",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CallingCardAccepted",
        kind: NotificationKind::Tip,
        message_key: "notification-calling-card-accepted",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CallingCardDeclined",
        kind: NotificationKind::Tip,
        message_key: "notification-calling-card-declined",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OfferFriendshipNoMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-offer-friendship-no-message",
        title_key: Some("notification-title-friendship-offer-from-name-label"),
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACCEPT_DECLINE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendshipOffered",
        kind: NotificationKind::Notify,
        message_key: "notification-friendship-offered",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendshipAccepted",
        kind: NotificationKind::Notify,
        message_key: "notification-friendship-accepted",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendshipDeclined",
        kind: NotificationKind::Notify,
        message_key: "notification-friendship-declined",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendshipAcceptedByMe",
        kind: NotificationKind::Notify,
        message_key: "notification-friendship-accepted-by-me",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FriendshipDeclinedByMe",
        kind: NotificationKind::Notify,
        message_key: "notification-friendship-declined-by-me",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutoUnmuteByIM",
        kind: NotificationKind::Notify,
        message_key: "notification-auto-unmute-by-im",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutoUnmuteByMoney",
        kind: NotificationKind::Notify,
        message_key: "notification-auto-unmute-by-money",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutoUnmuteByInventory",
        kind: NotificationKind::Notify,
        message_key: "notification-auto-unmute-by-inventory",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ZoomToAvatarNotPossible",
        kind: NotificationKind::AlertModal,
        message_key: "notification-zoom-to-avatar-not-possible",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TrackAvatarNotPossible",
        kind: NotificationKind::AlertModal,
        message_key: "notification-track-avatar-not-possible",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RadarAlert",
        kind: NotificationKind::Tip,
        message_key: "notification-radar-alert",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddNewContactSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-add-new-contact-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CREATE_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: Some("notification-add-new-contact-set-default"),
        }),
    },
    NotificationTemplate {
        name: "RemoveContactSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-contact-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-remove-contact-set"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RemoveContactFromSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-contact-from-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-remove-contact-from-set"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RemoveContactsFromSet",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-contacts-from-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-remove-contacts-from-set"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddToContactSetSingleSuccess",
        kind: NotificationKind::Notify,
        message_key: "notification-add-to-contact-set-single-success",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddToContactSetMultipleSuccess",
        kind: NotificationKind::Notify,
        message_key: "notification-add-to-contact-set-multiple-success",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetAvatarPseudonym",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-avatar-pseudonym",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CREATE_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "SetAvatarPseudonymMultiple",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-avatar-pseudonym-multiple",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CREATE_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "RenameContactSetFailure",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rename-contact-set-failure",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmGlobalOnlineStatusToggle",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-global-online-status-toggle",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GlobalOnlineStatusToggle",
        kind: NotificationKind::AlertModal,
        message_key: "notification-global-online-status-toggle",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-global-online-status-toggle"),
        form: OK_FORM,
        input: None,
    },
];
