//! IM & chat (viewer-notification-catalogue-im-chat).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    ACCEPT_DECLINE_MUTE_FORM, DELETE_LIST_CANCEL_FORM, NO_FORM, NotificationIgnore,
    NotificationInput, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_CANCEL_FORM, OK_FORM, REPLACE_CURRENT_LIST_USE_NEW_NAME_FORM, RESPOND_FORM,
    SET_NAME_CANCEL_FORM,
};

/// The IM & chat family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "FriendsAndGroupsOnly",
        kind: NotificationKind::AlertModal,
        message_key: "notification-friends-and-groups-only",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddAutoReplaceList",
        kind: NotificationKind::AlertModal,
        message_key: "notification-add-auto-replace-list",
        title_key: Some("notification-title-add-auto-replace-list"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: SET_NAME_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "listname",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "RenameAutoReplaceList",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rename-auto-replace-list",
        title_key: Some("notification-title-rename-auto-replace-list"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: REPLACE_CURRENT_LIST_USE_NEW_NAME_FORM,
        input: Some(NotificationInput {
            name: "listname",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "RemoveAutoReplaceList",
        kind: NotificationKind::AlertModal,
        message_key: "notification-remove-auto-replace-list",
        title_key: Some("notification-title-remove-auto-replace-list"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: DELETE_LIST_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidAutoReplaceEntry",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-auto-replace-entry",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidAutoReplaceList",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-auto-replace-list",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DoNotDisturbModeSet",
        kind: NotificationKind::Alert,
        message_key: "notification-do-not-disturb-mode-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-do-not-disturb-mode-set"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutorespondModeSet",
        kind: NotificationKind::Alert,
        message_key: "notification-autorespond-mode-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-autorespond-mode-set"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AutorespondNonFriendsModeSet",
        kind: NotificationKind::Alert,
        message_key: "notification-autorespond-non-friends-mode-set",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-autorespond-non-friends-mode-set"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmAddingChatParticipants",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-adding-chat-participants",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-adding-chat-participants"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ChatterBoxSessionStartError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-chatter-box-session-start-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    // reference notifytip with a form; a tip renders no buttons here, so Notify.
    NotificationTemplate {
        name: "ChatterBoxSessionEventError",
        kind: NotificationKind::Notify,
        message_key: "notification-chatter-box-session-event-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ForceCloseChatterBoxSession",
        kind: NotificationKind::AlertModal,
        message_key: "notification-force-close-chatter-box-session",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ChatSystemMessageTip",
        kind: NotificationKind::Tip,
        message_key: "notification-chat-system-message-tip",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: true,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "IMSystemMessageTip",
        kind: NotificationKind::Tip,
        message_key: "notification-im-system-message-tip",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "IMAcrossParentEstates",
        kind: NotificationKind::Tip,
        message_key: "notification-im-across-parent-estates",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ObjectMessage",
        kind: NotificationKind::Tip,
        message_key: "notification-object-message",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ServerObjectMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-server-object-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InviteAdHoc",
        kind: NotificationKind::Notify,
        message_key: "notification-invite-ad-hoc",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACCEPT_DECLINE_MUTE_FORM,
        input: None,
    },
    // reference type="notifytoast", mapped to Notify.
    NotificationTemplate {
        name: "IMToast",
        kind: NotificationKind::Notify,
        message_key: "notification-im-toast",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: RESPOND_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmCloseAll",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-close-all",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-close-all"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TextChatIsMutedByModerator",
        kind: NotificationKind::AlertModal,
        message_key: "notification-text-chat-is-muted-by-moderator",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ChatHistoryIsBusyAlert",
        kind: NotificationKind::AlertModal,
        message_key: "notification-chat-history-is-busy-alert",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PreferenceChatClearLog",
        kind: NotificationKind::AlertModal,
        message_key: "notification-preference-chat-clear-log",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-preference-chat-clear-log"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PreferenceChatDeleteTranscripts",
        kind: NotificationKind::AlertModal,
        message_key: "notification-preference-chat-delete-transcripts",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-preference-chat-delete-transcripts"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PreferenceChatPathChanged",
        kind: NotificationKind::Alert,
        message_key: "notification-preference-chat-path-changed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-preference-chat-path-changed"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AntiSpamBlocked",
        kind: NotificationKind::Tip,
        message_key: "notification-anti-spam-blocked",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: true,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AntiSpamImNewLineFloodBlocked",
        kind: NotificationKind::Tip,
        message_key: "notification-anti-spam-im-new-line-flood-blocked",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: true,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AntiSpamChatNewLineFloodBlocked",
        kind: NotificationKind::Tip,
        message_key: "notification-anti-spam-chat-new-line-flood-blocked",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: true,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SnoozeDuration",
        kind: NotificationKind::AlertModal,
        message_key: "notification-snooze-duration",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "duration",
            default_key: Some("notification-snooze-duration-default"),
        }),
    },
    NotificationTemplate {
        name: "SnoozeDurationInvalidInput",
        kind: NotificationKind::AlertModal,
        message_key: "notification-snooze-duration-invalid-input",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ChatHistoryIsMissing",
        kind: NotificationKind::AlertModal,
        message_key: "notification-chat-history-is-missing",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
];
