//! Landmarks & navigation (viewer-notification-catalogue-landmarks-navigation).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    DETAILS_CANCEL_FORM, NO_FORM, NotificationIgnore, NotificationInput, NotificationKind,
    NotificationPriority, NotificationTemplate, OK_CANCEL_FORM, OK_FORM, YES_NO_CANCEL_FORM,
};

/// The landmarks & navigation family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "PromptGoToEventsPage",
        kind: NotificationKind::AlertModal,
        message_key: "notification-prompt-go-to-events-page",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LandmarkAlreadyExists",
        kind: NotificationKind::Alert,
        message_key: "notification-landmark-already-exists",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LandmarkLocationUnknown",
        kind: NotificationKind::Alert,
        message_key: "notification-landmark-location-unknown",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotCreateLandmarkNotOwner",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-create-landmark-not-owner",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CreateLandmarkFolder",
        kind: NotificationKind::AlertModal,
        message_key: "notification-create-landmark-folder",
        title_key: Some("notification-title-create-folder"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "message",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "SeachFilteredOnShortWords",
        kind: NotificationKind::Tip,
        message_key: "notification-search-filtered-on-short-words",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SeachFilteredOnShortWordsEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-search-filtered-on-short-words-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RenameLandmark",
        kind: NotificationKind::AlertModal,
        message_key: "notification-rename-landmark",
        title_key: Some("notification-title-rename-landmark"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "new_name",
            default_key: Some("notification-rename-landmark-default"),
        }),
    },
    NotificationTemplate {
        name: "SetClassifiedMature",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-classified-mature",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetPickLocation",
        kind: NotificationKind::Alert,
        message_key: "notification-set-pick-location",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CopySLURL",
        kind: NotificationKind::AlertModal,
        message_key: "notification-copy-slurl",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-copy-slurl"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LandmarkMissing",
        kind: NotificationKind::Tip,
        message_key: "notification-landmark-missing",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnableToLoadLandmark",
        kind: NotificationKind::Tip,
        message_key: "notification-unable-to-load-landmark",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SearchWordBanned",
        kind: NotificationKind::Tip,
        message_key: "notification-search-word-banned",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoContentToSearch",
        kind: NotificationKind::Tip,
        message_key: "notification-no-content-to-search",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "EventNotification",
        kind: NotificationKind::Notify,
        message_key: "notification-event-notification",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: DETAILS_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LandSearchBlocked",
        kind: NotificationKind::Notify,
        message_key: "notification-land-search-blocked",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RegionDisallowsClassifieds",
        kind: NotificationKind::Notify,
        message_key: "notification-region-disallows-classifieds",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantCreateLandmarkForEvent",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-create-landmark-for-event",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantCreateLandmark",
        kind: NotificationKind::Notify,
        message_key: "notification-cant-create-landmark",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RegionTrackerAdd",
        kind: NotificationKind::Alert,
        message_key: "notification-region-tracker-add",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "label",
            default_key: Some("notification-region-tracker-add-default"),
        }),
    },
];
