//! Login & session (viewer-notification-catalogue-login-session).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    CONFIRM_AND_LOG_OUT_CANCEL_FORM, CONFIRM_CANCEL_FORM, CONTINUE_CANCEL_FORM,
    CREATE_A_NEW_ACCOUNT_TRY_AGAIN_FORM, CREATE_ACCOUNT_CONTINUE_FORM, INSTALL_SKIP_NOT_NOW_FORM,
    MALE_FEMALE_FORM, NO_FORM, NotificationIgnore, NotificationInput, NotificationKind,
    NotificationPriority, NotificationTemplate, OK_CANCEL_FORM, OK_FORM, OK_HELP_FORM,
    OK_HELP_TELEPORT_FORM, QUIT_FORM, RESET_REMIND_ME_NEXT_TIME_FORM,
};

/// The login & session family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "LoginFailedNoNetwork",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-failed-no-network",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginFailedToParse",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-failed-to-parse",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MustEnterPasswordToLogIn",
        kind: NotificationKind::AlertModal,
        message_key: "notification-must-enter-password-to-log-in",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MustHaveAccountToLogIn",
        kind: NotificationKind::AlertModal,
        message_key: "notification-must-have-account-to-log-in",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CREATE_A_NEW_ACCOUNT_TRY_AGAIN_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidCredentialFormat",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-credential-format",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidGrid",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-grid",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidLocationSLURL",
        kind: NotificationKind::AlertModal,
        message_key: "notification-invalid-location-slurl",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StartRegionEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-start-region-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FirstRun",
        kind: NotificationKind::AlertModal,
        message_key: "notification-first-run",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CREATE_ACCOUNT_CONTINUE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginCantRemoveUsername",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-cant-remove-username",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginCantRemoveCurUsername",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-cant-remove-cur-username",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CONFIRM_AND_LOG_OUT_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginPacketNeverReceived",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-packet-never-received",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_HELP_TELEPORT_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginPacketNeverReceivedNoTP",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-packet-never-received-no-tp",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_HELP_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginRemoveMultiGridUserData",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-remove-multi-grid-user-data",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CONFIRM_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WelcomeChooseSex",
        kind: NotificationKind::AlertModal,
        message_key: "notification-welcome-choose-sex",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: MALE_FEMALE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RequiredUpdate",
        kind: NotificationKind::AlertModal,
        message_key: "notification-required-update",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PauseForUpdate",
        kind: NotificationKind::AlertModal,
        message_key: "notification-pause-for-update",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DownloadingUpdate",
        kind: NotificationKind::AlertModal,
        message_key: "notification-downloading-update",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OptionalUpdateReady",
        kind: NotificationKind::AlertModal,
        message_key: "notification-optional-update-ready",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PromptOptionalUpdate",
        kind: NotificationKind::Alert,
        message_key: "notification-prompt-optional-update",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: INSTALL_SKIP_NOT_NOW_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "LoginFailedUnknown",
        kind: NotificationKind::AlertModal,
        message_key: "notification-login-failed-unknown",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: QUIT_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CapsKeyOn",
        kind: NotificationKind::Tip,
        message_key: "notification-caps-key-on",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FailedToGetBenefits",
        kind: NotificationKind::AlertModal,
        message_key: "notification-failed-to-get-benefits",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoConnect",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-connect",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_NOT_PERMITTED",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-not-permitted",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_CONNECT_ERROR",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-connect-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_NOT_ACCEPTABLE",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-not-acceptable",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_AUTH_FAIL",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-auth-fail",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_UDP_FWD_NOT_GRANTED",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-udp-fwd-not-granted",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_HOST_CONNECT_FAILED",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-host-connect-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_UNKNOWN_STATUS",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-unknown-status",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SOCKS_INVALID_HOST",
        kind: NotificationKind::AlertModal,
        message_key: "notification-socks-invalid-host",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmRemoveGrid",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-remove-grid",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-remove-grid"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CanNotRemoveConnectedGrid",
        kind: NotificationKind::AlertModal,
        message_key: "notification-can-not-remove-connected-grid",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-can-not-remove-connected-grid"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "BlockLoginInfo",
        kind: NotificationKind::AlertModal,
        message_key: "notification-block-login-info",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TestversionExpired",
        kind: NotificationKind::AlertModal,
        message_key: "notification-testversion-expired",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CantAddGrid",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cant-add-grid",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmRemoveCredential",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-remove-credential",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "PromptMFAToken",
        kind: NotificationKind::AlertModal,
        message_key: "notification-prompt-mfa-token",
        title_key: Some("notification-title-prompt-for-mfa-token"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: CONTINUE_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "token",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "PromptMFATokenWithSave",
        kind: NotificationKind::AlertModal,
        message_key: "notification-prompt-mfa-token-with-save",
        title_key: Some("notification-title-prompt-for-mfa-token"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::CheckboxOnly,
        ignore_key: Some("notification-ignoretext-prompt-mfa-token-with-save"),
        form: CONTINUE_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "token",
            default_key: None,
        }),
    },
    NotificationTemplate {
        name: "WarnForceLoginURL",
        kind: NotificationKind::AlertModal,
        message_key: "notification-warn-force-login-url",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: RESET_REMIND_ME_NEXT_TIME_FORM,
        input: None,
    },
];
