//! Marketplace (viewer-notification-catalogue-marketplace).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    MOVE_ITEMS_DONT_MOVE_ITEMS_CANCEL_FORM, MOVE_ITEMS_DONT_MOVE_ITEMS_FORM, NotificationIgnore,
    NotificationKind, NotificationPriority, NotificationTemplate, OK_CANCEL_FORM, OK_FORM,
};

/// The marketplace family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "ConfirmNoCopyToOutbox",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-no-copy-to-outbox",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: MOVE_ITEMS_DONT_MOVE_ITEMS_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutboxFolderCreated",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outbox-folder-created",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-outbox-folder-created"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutboxImportComplete",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outbox-import-complete",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-outbox-import-complete"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutboxImportHadErrors",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outbox-import-had-errors",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutboxImportFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outbox-import-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "OutboxInitFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-outbox-init-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StockPasteFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-stock-paste-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantPasteFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-paste-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantTransactionFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-transaction-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantUnprocessableEntity",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-unprocessable-entity",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantListingFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-listing-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantFolderActivationFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-folder-activation-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MerchantForceValidateListing",
        kind: NotificationKind::AlertModal,
        message_key: "notification-merchant-force-validate-listing",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-merchant-force-validate-listing"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmMerchantActiveChange",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-merchant-active-change",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-merchant-active-change"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmMerchantMoveInventory",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-merchant-move-inventory",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-merchant-move-inventory"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmListingCutOrDelete",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-listing-cut-or-delete",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-listing-cut-or-delete"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmCopyToMarketplace",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-copy-to-marketplace",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-copy-to-marketplace"),
        form: MOVE_ITEMS_DONT_MOVE_ITEMS_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmMerchantUnlist",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-merchant-unlist",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-merchant-unlist"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmMerchantClearVersion",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-merchant-clear-version",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-merchant-clear-version"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantListingNotUpdated",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-listing-not-updated",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantListingCannotWear",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-listing-cannot-wear",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantListingInvalidID",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-listing-invalid-id",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantListingActivateRequired",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-listing-activate-required",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-alert-merchant-listing-activate-required"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantStockFolderSplit",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-stock-folder-split",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-alert-merchant-stock-folder-split"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantStockFolderEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-stock-folder-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-alert-merchant-stock-folder-empty"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AlertMerchantVersionFolderEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-alert-merchant-version-folder-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-alert-merchant-version-folder-empty"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SLM_UPDATE_FOLDER",
        kind: NotificationKind::AlertModal,
        message_key: "notification-slm-update-folder",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
];
