//! Media & sound (viewer-notification-catalogue-media-sound).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    ACTION_NOW_CONDITION_ALLOW_THIS_DOMAIN_CONDITION_ALLOW_THIS_URL_FORM, ADD_CANCEL_FORM,
    ALLOW_DENY_BLACKLIST_WHITELIST_FORM, ALLOW_DENY_FORM, ENABLE_DISABLE_FORM, NO_FORM,
    NotificationIgnore, NotificationInput, NotificationKind, NotificationPriority,
    NotificationTemplate, OK_CANCEL_FORM, OK_FORM, PLAY_DONT_PLAY_FORM,
    PLAY_MEDIA_NOW_ALWAYS_PLAY_MEDIA_DO_NOT_PLAY_MEDIA_FORM, YES_NO_FORM,
};

/// The media & sound family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "MultipleFacesSelected",
        kind: NotificationKind::AlertModal,
        message_key: "notification-multiple-faces-selected",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-multiple-faces-selected"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DeleteMedia",
        kind: NotificationKind::AlertModal,
        message_key: "notification-delete-media",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-delete-media"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotUploadSoundFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-upload-sound-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileNotRIFF",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-not-riff",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileNotPCM",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-not-pcm",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidChannelCount",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-channel-count",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidSampleRate",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-sample-rate",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidWordSize",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-word-size",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidHeader",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-header",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidChunkSize",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-chunk-size",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SoundFileInvalidTooLong",
        kind: NotificationKind::AlertModal,
        message_key: "notification-sound-file-invalid-too-long",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "CannotOpenTemporarySoundFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-open-temporary-sound-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnknownVorbisEncodeFailure",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unknown-vorbis-encode-failure",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ParcelCanPlayMedia",
        kind: NotificationKind::AlertModal,
        message_key: "notification-parcel-can-play-media",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: PLAY_MEDIA_NOW_ALWAYS_PLAY_MEDIA_DO_NOT_PLAY_MEDIA_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ParcelPlayingMedia",
        kind: NotificationKind::Notify,
        message_key: "notification-parcel-playing-media",
        title_key: Some("notification-title-parcel-is-playing-media"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::CheckboxOnly,
        ignore_key: Some("notification-ignoretext-parcel-playing-media"),
        form: PLAY_DONT_PLAY_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "EnableMediaFilter",
        kind: NotificationKind::Alert,
        message_key: "notification-enable-media-filter",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ENABLE_DISABLE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MediaAlert",
        kind: NotificationKind::Alert,
        message_key: "notification-media-alert",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ALLOW_DENY_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MediaAlert2",
        kind: NotificationKind::Alert,
        message_key: "notification-media-alert2",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACTION_NOW_CONDITION_ALLOW_THIS_DOMAIN_CONDITION_ALLOW_THIS_URL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MediaAlertSingle",
        kind: NotificationKind::Alert,
        message_key: "notification-media-alert-single",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ALLOW_DENY_BLACKLIST_WHITELIST_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AudioAlert",
        kind: NotificationKind::Alert,
        message_key: "notification-audio-alert",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ALLOW_DENY_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AudioAlert2",
        kind: NotificationKind::Alert,
        message_key: "notification-audio-alert2",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACTION_NOW_CONDITION_ALLOW_THIS_DOMAIN_CONDITION_ALLOW_THIS_URL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AudioAlertSingle",
        kind: NotificationKind::Alert,
        message_key: "notification-audio-alert-single",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ALLOW_DENY_BLACKLIST_WHITELIST_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoQuickTime",
        kind: NotificationKind::Notify,
        message_key: "notification-no-quick-time",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoPlugin",
        kind: NotificationKind::Notify,
        message_key: "notification-no-plugin",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MediaPluginFailed",
        kind: NotificationKind::AlertModal,
        message_key: "notification-media-plugin-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-media-plugin-failed"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ObjectMediaFailure",
        kind: NotificationKind::AlertModal,
        message_key: "notification-object-media-failure",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StreamListExportSuccess",
        kind: NotificationKind::Notify,
        message_key: "notification-stream-list-export-success",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StreamListImportSuccess",
        kind: NotificationKind::Notify,
        message_key: "notification-stream-list-import-success",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StreamMetadata",
        kind: NotificationKind::Tip,
        message_key: "notification-stream-metadata",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "StreamMetadataNoArtist",
        kind: NotificationKind::Tip,
        message_key: "notification-stream-metadata-no-artist",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AddToMediaList",
        kind: NotificationKind::AlertModal,
        message_key: "notification-add-to-media-list",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ADD_CANCEL_FORM,
        input: Some(NotificationInput {
            name: "url",
            default_key: None,
        }),
    },
];
