//! Miscellaneous (viewer-notification-catalogue-misc).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM, SAVE_DISCARD_CANCEL_FORM, YES_CANCEL_FORM,
};

/// The miscellaneous family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "GenericAlertYesCancel",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-alert-yes-cancel",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericAlertOK",
        kind: NotificationKind::AlertModal,
        message_key: "notification-generic-alert-ok",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "InvalidKeystroke",
        kind: NotificationKind::Tip,
        message_key: "notification-invalid-keystroke",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SaveChanges",
        kind: NotificationKind::AlertModal,
        message_key: "notification-save-changes",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: SAVE_DISCARD_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoFrontmostFloater",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-frontmost-floater",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ErrorMessage",
        kind: NotificationKind::AlertModal,
        message_key: "notification-error-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SystemMessageTip",
        kind: NotificationKind::Tip,
        message_key: "notification-system-message-tip",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "Cancelled",
        kind: NotificationKind::Tip,
        message_key: "notification-cancelled",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DeactivatedGesturesTrigger",
        kind: NotificationKind::Notify,
        message_key: "notification-deactivated-gestures-trigger",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GodMessage",
        kind: NotificationKind::Notify,
        message_key: "notification-god-message",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MaxListSelectMessage",
        kind: NotificationKind::Tip,
        message_key: "notification-max-list-select-message",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GodlikeRequestFailed",
        kind: NotificationKind::Notify,
        message_key: "notification-godlike-request-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GenericRequestFailed",
        kind: NotificationKind::Notify,
        message_key: "notification-generic-request-failed",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SpecialPowersRequestFailedLogged",
        kind: NotificationKind::Notify,
        message_key: "notification-special-powers-request-failed-logged",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ExpireExplanation",
        kind: NotificationKind::Notify,
        message_key: "notification-expire-explanation",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DieExplanation",
        kind: NotificationKind::Notify,
        message_key: "notification-die-explanation",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "RegExFail",
        kind: NotificationKind::AlertModal,
        message_key: "notification-reg-ex-fail",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WhitelistReminder",
        kind: NotificationKind::AlertModal,
        message_key: "notification-whitelist-reminder",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
];
