//! Premium account (viewer-notification-catalogue-premium-account).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM, YES_NO_BUTTONS_FORM,
};

/// The premium account family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "SetDisplayNameSuccess",
        kind: NotificationKind::Alert,
        message_key: "notification-set-display-name-success",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetDisplayNameBlocked",
        kind: NotificationKind::Alert,
        message_key: "notification-set-display-name-blocked",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetDisplayNameFailedLength",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-display-name-failed-length",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetDisplayNameFailedGeneric",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-display-name-failed-generic",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "SetDisplayNameMismatch",
        kind: NotificationKind::AlertModal,
        message_key: "notification-set-display-name-mismatch",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AgentDisplayNameUpdateThresholdExceeded",
        kind: NotificationKind::AlertModal,
        message_key: "notification-agent-display-name-update-threshold-exceeded",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AgentDisplayNameSetBlocked",
        kind: NotificationKind::AlertModal,
        message_key: "notification-agent-display-name-set-blocked",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AgentDisplayNameSetInvalidUnicode",
        kind: NotificationKind::AlertModal,
        message_key: "notification-agent-display-name-set-invalid-unicode",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "AgentDisplayNameSetOnlyPunctuation",
        kind: NotificationKind::AlertModal,
        message_key: "notification-agent-display-name-set-only-punctuation",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DisplayNameUpdate",
        kind: NotificationKind::Tip,
        message_key: "notification-display-name-update",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "DisplayNameUpdateRemoveAlias",
        kind: NotificationKind::Notify,
        message_key: "notification-display-name-update-remove-alias",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: YES_NO_BUTTONS_FORM,
        input: None,
    },
];
