//! Security (viewer-notification-catalogue-security).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM, TRUST_CANCEL_FORM,
};

/// The security family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "CorruptedProtectedDataStore",
        kind: NotificationKind::AlertModal,
        message_key: "notification-corrupted-protected-data-store",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GeneralCertificateErrorShort",
        kind: NotificationKind::AlertModal,
        message_key: "notification-general-certificate-error-short",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GeneralCertificateError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-general-certificate-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TrustCertificateError",
        kind: NotificationKind::AlertModal,
        message_key: "notification-trust-certificate-error",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: TRUST_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseConfirm",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-confirm",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseSelectCategory",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-select-category",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseAbuserNameEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-abuser-name-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseAbuserLocationEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-abuser-location-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseSummaryEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-summary-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseDetailsEmpty",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-details-empty",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "HelpReportAbuseContainsCopyright",
        kind: NotificationKind::AlertModal,
        message_key: "notification-help-report-abuse-contains-copyright",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NotAgeVerified",
        kind: NotificationKind::AlertModal,
        message_key: "notification-not-age-verified",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-not-age-verified"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NotAgeVerified_Notify",
        kind: NotificationKind::Tip,
        message_key: "notification-not-age-verified-notify",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "BlockedSLURL",
        kind: NotificationKind::Tip,
        message_key: "notification-blocked-slurl",
        title_key: None,
        priority: NotificationPriority::High,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ThrottledSLURL",
        kind: NotificationKind::Tip,
        message_key: "notification-throttled-slurl",
        title_key: None,
        priority: NotificationPriority::High,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
