//! UI hints (viewer-notification-catalogue-ui-hints).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority, NotificationTemplate,
    OK_FORM,
};

/// The UI hints family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "TutorialNotFound",
        kind: NotificationKind::AlertModal,
        message_key: "notification-tutorial-not-found",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "TeleportToLandmark",
        kind: NotificationKind::Tip,
        message_key: "notification-teleport-to-landmark",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnableToFindHelpTopic",
        kind: NotificationKind::AlertModal,
        message_key: "notification-unable-to-find-help-topic",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintChat",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-chat",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintSit",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-sit",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintSpeak",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-speak",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintDestinationGuide",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-destination-guide",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintSidePanel",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-side-panel",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintMove",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-move",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintMoveClick",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-move-click",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintDisplayName",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-display-name",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintView",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-view",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintInventory",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-inventory",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    // reference type="hint", mapped to Tip.
    NotificationTemplate {
        name: "HintLindenDollar",
        kind: NotificationKind::Tip,
        message_key: "notification-hint-linden-dollar",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "FirstUseFlyOverride",
        kind: NotificationKind::AlertModal,
        message_key: "notification-first-use-fly-override",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
];
