//! Voice (viewer-notification-catalogue-voice).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    ACCEPT_DECLINE_MUTE_FORM, NO_FORM, NotificationIgnore, NotificationKind, NotificationPriority,
    NotificationTemplate, OK_CANCEL_FORM, OK_FORM, YES_NO_FORM,
};

/// The voice family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "VoiceVersionMismatch",
        kind: NotificationKind::AlertModal,
        message_key: "notification-voice-version-mismatch",
        title_key: Some("notification-title-voice-version-mismatch"),
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceInviteP2P",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-invite-p2-p",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACCEPT_DECLINE_MUTE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceInviteGroup",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-invite-group",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACCEPT_DECLINE_MUTE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceInviteAdHoc",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-invite-ad-hoc",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: ACCEPT_DECLINE_MUTE_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceChannelFull",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-channel-full",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ProximalVoiceChannelFull",
        kind: NotificationKind::Tip,
        message_key: "notification-proximal-voice-channel-full",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceChannelDisconnected",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-channel-disconnected",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceChannelDisconnectedP2P",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-channel-disconnected-p2-p",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "P2PCallDeclined",
        kind: NotificationKind::Tip,
        message_key: "notification-p2-p-call-declined",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "P2PCallNoAnswer",
        kind: NotificationKind::Tip,
        message_key: "notification-p2-p-call-no-answer",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceChannelJoinFailed",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-channel-join-failed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceEffectsExpired",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-effects-expired",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceEffectsExpiredInUse",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-effects-expired-in-use",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceEffectsWillExpire",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-effects-will-expire",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-voice-effects-will-expire"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceEffectsNew",
        kind: NotificationKind::Notify,
        message_key: "notification-voice-effects-new",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceEffectsNotSupported",
        kind: NotificationKind::AlertModal,
        message_key: "notification-voice-effects-not-supported",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-voice-effects-not-supported"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceNotAllowed",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-not-allowed",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceCallGenericError",
        kind: NotificationKind::Tip,
        message_key: "notification-voice-call-generic-error",
        title_key: None,
        priority: NotificationPriority::Low,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "VoiceIsMutedByModerator",
        kind: NotificationKind::AlertModal,
        message_key: "notification-voice-is-muted-by-moderator",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoVoiceConnect",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-voice-connect",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-no-voice-connect"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "NoVoiceConnect-GIAB",
        kind: NotificationKind::AlertModal,
        message_key: "notification-no-voice-connect-giab",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmLeaveCall",
        kind: NotificationKind::AlertModal,
        message_key: "notification-confirm-leave-call",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-leave-call"),
        form: YES_NO_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "ConfirmMuteAll",
        kind: NotificationKind::Alert,
        message_key: "notification-confirm-mute-all",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-confirm-mute-all"),
        form: OK_CANCEL_FORM,
        input: None,
    },
];
