//! Web browser (viewer-notification-catalogue-web-browser).
//!
//! One family of [the catalogue](crate::NOTIFICATIONS), joined into it
//! in source order by `catalogue`.

use crate::{
    GO_TO_PAGE_CANCEL_FORM, LATER_GO_NOW_FORM, NO_FORM, NotificationIgnore, NotificationKind,
    NotificationPriority, NotificationTemplate, OK_CANCEL_FORM, OK_FORM,
};

/// The web browser family's catalogue entries.
pub(crate) const ENTRIES: &[NotificationTemplate] = &[
    NotificationTemplate {
        name: "CannotDownloadFile",
        kind: NotificationKind::AlertModal,
        message_key: "notification-cannot-download-file",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "MediaFileDownloadUnsupported",
        kind: NotificationKind::Alert,
        message_key: "notification-media-file-download-unsupported",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: true,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-media-file-download-unsupported"),
        form: OK_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchExternalTarget",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-external-target",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-external-target"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchJoinNow",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-join-now",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-join-now"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchSecurityIssues",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-security-issues",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-security-issues"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchQAWiki",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-qa-wiki",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-qa-wiki"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchPublicIssue",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-public-issue",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-public-issue"),
        form: GO_TO_PAGE_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchSupportWiki",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-support-wiki",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-support-wiki"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchLSLGuide",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-lsl-guide",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-lsl-guide"),
        form: OK_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchLSLWiki",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-lsl-wiki",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-lsl-wiki"),
        form: GO_TO_PAGE_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "WebLaunchAccountHistory",
        kind: NotificationKind::AlertModal,
        message_key: "notification-web-launch-account-history",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::DefaultResponse,
        ignore_key: Some("notification-ignoretext-web-launch-account-history"),
        form: GO_TO_PAGE_CANCEL_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "GotoURL",
        kind: NotificationKind::Notify,
        message_key: "notification-goto-url",
        title_key: None,
        priority: NotificationPriority::Normal,
        persist: true,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: LATER_GO_NOW_FORM,
        input: None,
    },
    NotificationTemplate {
        name: "UnsupportedCommandSLURL",
        kind: NotificationKind::Tip,
        message_key: "notification-unsupported-command-slurl",
        title_key: None,
        priority: NotificationPriority::High,
        persist: false,
        log_to_chat: false,
        unique: false,
        ignore: NotificationIgnore::None,
        ignore_key: None,
        form: NO_FORM,
        input: None,
    },
];
